 //Endopoint for host of ApiGateway
# @baseUrl = http://localhost:4000  
@baseUrl = http://growvia.com  
@urlPath = api/gateway/v1/auth

GET {{baseUrl}}/gateway-health
Content-Type: application/json
Accept: application/json
withCredentials:true


//Post Request to -> http://localhost:4002/app/v1//auth/signup
//this is directly to the Auth service (4002) wont work because the request is comming from the Client (dirrectly)
//The request must be sent to the ApiGateway (which it will verify and sent it to Auth Service)
//@baseUrl = http://localhost:4002  


############### SIGNUP / REGISTER

# //Post Request to -> http://localhost:4000/app/v1/gateway/auth/signup
# POST {{baseUrl}}/{{urlPath}}/signup
# Content-Type: application/json
# Accept: application/json
# withCredentials:true

# //This post request requires data to be passed to the body (object)
# {
#     "username": "novak12",
#     "email": "novak12@gmail.com",
#     "password": "novak12",
#     "profilePicture": "Something"
# }



####### SIGNIN / LOGIN
# "username": "Lazar",
# "password": "LazarPassword"

# "username": "novak12",
# "password": "novak12"

# "username": "sara22",
# "email": "sara22.vec@gmail.com",
# "password": "sara22",



# POST {{baseUrl}}/{{urlPath}}/signin
# Content-Type: application/json
# Accept: application/json
# withCredentials:true

# //This post request requires data to be passed to the body (object)
# {
#     "usernameOrEmail": "novak12",
#     "password": "novak12"
# }


# PUT {{baseUrl}}/{{urlPath}}/forgot-password
# Content-Type: application/json
# Accept: application/json
# withCredentials:true

# #email will be requred 
# {   
#     //"email": "novak12@gmail.com"
#     "email": "laza@gmail.com"
# }


# PUT {{baseUrl}}/{{urlPath}}/verify-email
# Content-Type: application/json
# Accept: application/json
# withCredentials:true

# //This post request requires data to be passed to the body (object)
# {   
#     "userID": 2
# }

## Or PUT Request with "id value" in the url (without passing value in body)
#PUT {{baseUrl}}/{{urlPath}}/verify-email/1
#Content-Type: application/json
#Accept: application/json
#withCredentials:true


# PUT {{baseUrl}}/{{urlPath}}/change-password
# Content-Type: application/json
# Accept: application/json
# withCredentials:true

# //This post request requires data to be passed to the body (object)
# //but userID will be get throught currentUser.id -> Logged User
# {   
#     "newPassword": "novak13"   
# }


# @token = 852b3edfffd5b9fc551ad405b01854a9b2a1f45a79809b56fc5c517ee24fb971
# # Reset Password for (novak12) to
# # PUT {{baseUrl}}/{{urlPath}}/reset-password/852b3edfffd5b9fc551ad405b01854a9b2a1f45a79809b56fc5c517ee24fb971
# PUT {{baseUrl}}/{{urlPath}}/reset-password/{{token}}
# Content-Type: application/json
# Accept: application/json
# withCredentials:true

# //This post request requires data to be passed to the body (object)
# {   
#     "password": "novak13",
#     "repeatedPassword": "novak13"
# }