@baseUrl = http://localhost:4000  
@urlPath = api/gateway/v1/auth

//reserpasswordtoken
@token = 070b055dd66d2dd2a859789557c63998f7f10a0f499c1514e328de57ba479bba

# Reset Password for (novak12) to
# PUT {{baseUrl}}/{{urlPath}}/reset-password/852b3edfffd5b9fc551ad405b01854a9b2a1f45a79809b56fc5c517ee24fb971
PUT {{baseUrl}}/{{urlPath}}/reset-password/{{token}}
Content-Type: application/json
Accept: application/json
withCredentials:true

//This post request requires data to be passed to the body (object)
{   
    "password": "sara22",
    "repeatedPassword": "sara22"
} 