@baseUrl = http://localhost:4000  
@urlPath = api/gateway/v1/auth

PUT {{baseUrl}}/{{urlPath}}/change-password
Content-Type: application/json
Accept: application/json
withCredentials:true

//This post request requires data to be passed to the body (object)
//but userID will be get throught currentUser.id -> Logged User
{   
    "newPassword": "novak13"   
}
