@baseUrl = http://localhost:4000  
@urlPath = api/gateway/v1/auth

PUT {{baseUrl}}/{{urlPath}}/resend-verification
Content-Type: application/json
Accept: application/json
withCredentials:true

//after login.http the jwtToken will be in the session => req.session.jwtToken
