apiVersion: apps/v1
kind: Deployment
metadata:
  name: growvia-payment
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: growvia-payment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: growvia-payment
    spec:
      containers:
      - name: growvia-payment
        image: veckovn/growvia-payment:stable
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            cpu: 100m
            memory: 150Mi
        ports:
        - name: payment
          containerPort: 4006
        env:
          - name: ENALBE_APM
            value: '1'
          - name: NODE_ENV
            value: 'production'
          - name: CLIENT_URL
            value: "http://localhost:3000"
          - name: API_GATEWAY_URL
            value: "http://growvia-gateway.production.svc.cluster.local:4000"
          - name: ELASTICSEARCH_URL
            valueFrom:
              secretKeyRef:
                name: secret-data
                key: growvia-elastic-url
          - name: ELASTICSEARCH_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: secret-data
                key: growvia-elastic-apm-server-url          
          - name: ELASTICSEARCH_APM_TOKEN
            valueFrom:
              secretKeyRef:
                name: secret-data
                key: growvia-elastic-apm-token                
          - name: STRIPE_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: secret-data
                key: stripe-secret-key     
          - name: RABBITMQ_AMQP_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: secret-data
                key: growvia-rabbitmq-endpoint            
          - name: GATEWAY_JWT_TOKEN 
            valueFrom:
              secretKeyRef:
                name: secret-data
                key: gateway-jwt-token
          - name: JWT_TOKEN
            valueFrom:
              secretKeyRef:
                name: secret-data
                key: jwt-token