apiVersion: v1
kind: Service
metadata:
  name: growvia-payment
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: growvia-payment
  ports:
  - name: payment
    port: 4006
    targetPort: 4006
    protocol: TCP