apiVersion: v1
kind: Service
metadata:
  name: growvia-product
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: growvia-product
  ports:
  - name: product
    port: 4004
    targetPort: 4004
    protocol: TCP