apiVersion: v1
kind: Service
metadata:
  name: growvia-authentication
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: growvia-authentication
  ports:
  - name: authentication
    port: 4002
    targetPort: 4002
    protocol: TCP