apiVersion: v1
kind: Secret
metadata:
  name: secret-data
  namespace: production
type: Opaque
# all these key-values can be viewed with admin permision
data:
  #key - value(64encoded string)
  gateway-jwt-token: Mjk0YmMwZGQ1YmFhYjgxM2M1Zjc2MmMzYThiYmExNTc=
  jwt-token: MGM0MWNjNWMzNDc5ZDE2Y2IyNzhkNWUwNjZiN2ZmNWM=
  first-secret-key: MTBkYzBkYThiMmRkMDQxYjc4YTgyODU1MWNhNzNjYTA=
  second-secret-key: YTI3ZjNmNzIyNDM1NzIwZGQ1NzU4YmJmMDJlNjA1NWM=
  test-email-name: RGFuaWthIFByaWNl
  test-email: ZGFuaWthLnByaWNlOTNAZXRoZXJlYWwuZW1haWw=
  test-email-password: QVM4blpCZkdYZERWaEd2WGgz
  cloudinary-name: ZHFsb3EwZzk3
  cloudinary-api-key: MTI5MTE0ODc4NjkyNzI0
  cloudinary-api-secret: ZTJBUlJicDhUZkNqX1JDaGdENUpfN21DZnpZ
  stripe-secret-key: c2tfdGVzdF81MVIzSElDR0RENjlKdVY0bVJuU0R4ZmlHZW5xSVRCYmFaUHpRQjRqUmp4WFF5d3RraEpGY1NBQml1SlROdHdDNktGU1Nxb1BqbHo2SW1mQjVEZlJvdFJsRDAwT1YwQXlXNHU=
  #redis-redis-host: redis://:redisConfigMapPassword@growvia-redis.production.svc.cluster.local:6379
  growvia-redis-host: cmVkaXM6Ly86cmVkaXNDb25maWdNYXBQYXNzd29yZEBncm93dmlhLXJlZGlzLnByb2R1Y3Rpb24uc3ZjLmNsdXN0ZXIubG9jYWw6NjM3OQ==
  #One Database more Collections
  #monogdb://growvia-mongo.production.svc.cluster.local:27017/'DBNAME'
  #growvia-mongodb-url: monogdb://growvia-mongo.production.svc.cluster.local:27017/
  growvia-mongodb-url: bW9ub2dkYjovL2dyb3d2aWEtbW9uZ28ucHJvZHVjdGlvbi5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNy8=
  
  #But i have 'user_db', 'product_db ' and notification_db" as DB instances in mongoDB
  #Don't have one DB that have those  collections
  #so decided to test (One MongoDB instanec, but they each use their own isolated database)
  #grwovia-mongo-user-url: mongodb://growvia-mongo.production.svc.cluster.local:27017/user_db
  grwovia-mongo-user-url: bW9uZ29kYjovL2dyb3d2aWEtbW9uZ28ucHJvZHVjdGlvbi5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNy91c2VyX2Ri
  
  #growvia-mongo-product-url: mongodb://growvia-mongo.production.svc.cluster.local:27017/product_db
  growvia-mongo-product-url: bW9uZ29kYjovL2dyb3d2aWEtbW9uZ28ucHJvZHVjdGlvbi5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNy9wcm9kdWN0X2Ri

  #growvia-mongo-notification-url: mongodb://growvia-mongo.production.svc.cluster.local:27017/notification_db
  growvia-mongo-notification-url: bW9uZ29kYjovL2dyb3d2aWEtbW9uZ28ucHJvZHVjdGlvbi5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNy9ub3RpZmljYXRpb25fZGI=

  #growvia-rabbitmq-endpoint: amqp://growvia:growviapassword@growvia-rabbtimq.production.svc.cluster.local:5672
  # growvia-rabbitmq-endpoint: YW1xcDovL2dyb3d2aWE6Z3Jvd3ZpYXBhc3N3b3JkQGdyb3d2aWEtcmFiYnRpbXEucHJvZHVjdGlvbi5zdmMuY2x1c3Rlci5sb2NhbDo1Njcy
  #growvia-rabbitmq-endpoint: amqp://growvia:growviapassword@growvia-rabbitmq.production.svc.cluster.local:5672 #THE CORRECT ONE ->
  growvia-rabbitmq-endpoint: YW1xcDovL2dyb3d2aWE6Z3Jvd3ZpYXBhc3N3b3JkQGdyb3d2aWEtcmFiYml0bXEucHJvZHVjdGlvbi5zdmMuY2x1c3Rlci5sb2NhbDo1Njcy

  growvia-rabbitmq-user: Z3Jvd3ZpYQ==
  growvia-rabbitmq-password: Z3Jvd3ZpYXBhc3N3b3Jk

  #pg - host is the label name in postgres service (service.yaml) => growvia-pg
  #growvia-postgres-host: growvia-pg
  growvia-postgres-host: Z3Jvd3ZpYS1wZw==
  growvia-postgres-user: Z3Jvd3ZpYQ==
  growvia-postgres-password: Z3Jvd3ZpYXBhc3M=


  # growvia-elastic-host: growvia-elastic.production.svc.cluster.local _> without port numeer
  growvia-elastic-host: Z3Jvd3ZpYS1lbGFzdGljLnByb2R1Y3Rpb24uc3ZjLmNsdXN0ZXIubG9jYWw=
  # growvia-elastic-username: elastic (same as default) 
  growvia-elastic-username: ZWxhc3RpYw==
  #growvia-elastic-password: adminelastic
  growvia-elastic-password: YWRtaW5lbGFzdGlj
  #growvia-elastic-url: http://elastic:adminelastic@growvia-elastic.production.svc.cluster.local:9200
  growvia-elastic-url: aHR0cDovL2VsYXN0aWM6YWRtaW5lbGFzdGljQGdyb3d2aWEtZWxhc3RpYy5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjkyMDA=
  #growvia-elastic-apm-server-url: http//growvia-elastic.production.svc.cluster.local:8200
  growvia-elastic-apm-server-url: aHR0cC8vZ3Jvd3ZpYS1lbGFzdGljLnByb2R1Y3Rpb24uc3ZjLmNsdXN0ZXIubG9jYWw6ODIwMA==
  growvia-elastic-apm-token: ''

  #used for kibana connection
  #growvia-elastic-hosts: http://growvia-elastic.production.svc.cluster.local:9200
  growvia-elastic-hosts: aHR0cDovL2dyb3d2aWEtZWxhc3RpYy5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjkyMDA=
  #growvia-elastic-kibana-username: kibana_system
  growvia-elastic-kibana-username: a2liYW5hX3N5c3RlbQ==
  #growvia-elastic-kibana-password: elastickibana 
  growvia-elastic-kibana-password: ZWxhc3RpY2tpYmFuYQ==
  # growvia-elastic-kibana-token: AAEAAWVsYXN0aWMva2liYW5hL2dyb3d2aWEta2liYW5hOmlhMFplaEFUU1A2cUVHWkNBS2FoQ0E
  growvia-elastic-kibana-token: QUFFQUFXVnNZWE4wYVdNdmEybGlZVzVoTDJkeWIzZDJhV0V0YTJsaVlXNWhPak5ZU2xwMWFrRkVWRVl0T0ZWaU9VRlpjVU16Vm1j
  