kind: Deployment
apiVersion: apps/v1
metadata:
  name: growvia-elastic
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: growvia-elastic
  minReadySeconds: 10
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: growvia-elastic
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: busybox
        image: busybox #tthe image that we can use to execute cmd
        imagePullPolicy: Always
        #shell cmd - We are setting permission to the folder
        command: ['sh', '-c', "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        volumeMounts:
        - name: elastic-storage
          mountPath: /usr/share/elasticsearch/data
      containers:
        - name: growvia-elastic
          image: docker.elastic.co/elasticsearch/elasticsearch:8.18.0 #Image that is used in local Docker
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1500m
              memory: 4Gi
            requests:
              cpu: 250m
              memory: 2Gi
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: '-Xmx1g -Xms1g'
            - name: bootstrap.memory_lock
              value: 'true'
            - name: xpack.security.enabled
              value: 'true'
            - name: xpack.security.http.ssl.enabled
              value: 'false'
            - name: xpack.security.transport.ssl.enabled
              value: 'false'
            - name: xpack.security.authc.api_key.enabled
              value: 'true'
            - name: xpack.monitoring.collection.enabled
              value: 'true'
            - name: xpack.security.enrollment.enabled
              value: 'true'
            - name: xpack.security.authc.token.enabled
              value: 'true'
            - name: ELASTIC_PASSWORD
              # value: 'adminelastic'
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: growvia-elastic-password
          ports:
          - name: growvia-elastic
            #The port that used to access Elastic
            containerPort: 9200
          volumeMounts:
            - name: elastic-storage
              mountPath: /usr/share/elasticsearch/data
              subPath: data
      volumes:
      - name: elastic-storage
        persistentVolumeClaim:
          claimName: elastic-pvc