apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-pv
  namespace: production
spec:
  storageClassName: elastic-storage
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-pvc
  namespace: production
spec:
  storageClassName: elastic-storage
  resources:
    requests:
      storage: 4Gi
  accessModes:
    - ReadWriteOnce