apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: growvia-mongo
  namespace: production
spec:
  selector:
    matchLabels:
      app: growvia-mongo
  serviceName: growvia-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: growvia-mongo
    spec:
      containers:
      - name: growvia-mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
          name: growvia-mongo
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc