# Reference -> https://sourcegraph.com/github.com/elastic/beats/-/blob/metricbeat/metricbeat.reference.yml
metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: docker
  #connect metrics to these componenets
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

#the host system that running on
- module: system
  metricsets:
    - cpu             # CPU usage
    - load            # CPU load averages
    - memory          # Memory usage
    - network         # Network IO
    - process         # Per process metrics
    - process_summary # Process summary
    - uptime          # System Uptime
    - socket_summary  # Socket summary
    - core            # Per CPU core usage
    - diskio          # Disk IO
    - filesystem      # File system usage for each mountpoint
    - fsstat          # File system summary metrics
    - socket          # Sockets and connection info (linux only)
  enabled: true
  period: 10s
  processes: ['.*']
  hostfs: "/hostfs"
  cpu.metrics:  ["percentages","normalized_percentages"]
  core.metrics: ["percentages"]


- module: rabbitmq
  metricsets: ["node", "queue", "connection", "exchange", "shovel"]
  enabled: true
  period: 10s
  hosts: ["127.0.0.1:15672"]

- module: mongodb
  metricsets: ["dbstats", "status", "collstats", "metrics", "replstatus"]
  period: 10s
  enabled: true
  # The hosts must be passed as MongoDB URLs in the format:
  # [mongodb://][user:pass@]host[:port].
  # The username and password can also be set using the respective configuration
  # options. The credentials in the URL take precedence over the username and
  # password configuration options.
  hosts: ["mongodb://127.0.0.1:27017"]

- module: postgresql
  enabled: true
  metricsets:
    - database
    - bgwriter
    - activity
  period: 10s
  hosts: ["postgres://127.0.0.1:5432"]
  username: growvia
  password: growviapass

processors:
  - add_cloud_metadata: ~

#ELASTICSEARCH_URL that used in services
#ELASTICSEARCH_URL=http://elastic:adminelastic@elasticsearch:9200

#!!!We sending metrics to ElasticSearch and the we view it on Kibana
output.elasticsearch:
  hosts: ['http://elasticsearch_container:9200']
  username: 'elastic'
  #defiend in elasticserach container as well
  password: 'adminelastic'