apiVersion: v1
kind: Service
metadata:
  name: growvia-notification
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: growvia-notification
  ports:
  - name: notification
    port: 4001
    targetPort: 4001
    protocol: TCP