apiVersion: apps/v1
kind: Deployment
metadata:
  name: growvia-kibana
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: growvia-kibana
  template:
    metadata:
      labels:
        app: growvia-kibana
    spec:
      containers:
        - name: growvia-kibana
          image: docker.elastic.co/kibana/kibana:8.18.0
          resources:
            limits:
              memory: "1Gi"
              cpu: "1250m"
            requests:
              cpu: 250m
              memory: 1Gi
          ports:
            - name: growvia-kibana
              containerPort: 5601    
          env:
            - name: ELASTICSEARCH_HOSTS
              #use elastic service name and specify 'production' namespace
              #value: http://growvia-elastic.production.svc.cluster.local:9200
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: growvia-elastic-hosts
            - name: ELASTICSEARCH_KIBANA_USERNAME
              #value: 'kibana_system'
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: growvia-elastic-kibana-username
            - name: ELASTICSEARCH_KIBANA_PASSWORD
              #value: 'elastickibana'
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: growvia-elastic-kibana-password
            - name: ELASTICSEARCH_SERVICEACCOUNTTOKEN
              #value: fresh generated 
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: growvia-elastic-kibana-token
          volumeMounts:
            - name: kibana-config
              mountPath: /usr/share/kibana/config
      volumes:
      #this must much name from volumeMounts (above)
      - name: kibana-config 
        configMap:
        #this must match configMap.yaml name (in this situation is the same as volumeMount)
          name: kibana-config 

