apiVersion: v1
kind: Service
metadata:
  name: growvia-order
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: growvia-order
  ports:
  - name: order
    port: 4005
    targetPort: 4005
    protocol: TCP