apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  #applied only to production namespace not to whole cluster
  namespace: production 

spec:
  # Value of metadata:name from storageClass.yaml
  storageClassName: postgres-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/postgresql/data"
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: production
spec:
  storageClassName: postgres-storage
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce