apiVersion: v1
kind: Service
metadata:
  name: growvia-pg
  namespace: production
spec:
  type: ClusterIP
  selector:
    #Every queue with this name ‘app:growvia-pg), 
    #We set ‘label’ tab to queue.yams as app:growvia-pg
    app: growvia-pg
  ports:
  # - name: queue
  - name: growvia-pg
    port: 5432
    targetPort: 5432