apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv 
  namespace: production
spec:
  #name of redis storageClass
  storageClassName: redis-storage 
  capacity:
    #give 1GB of storage for this volume
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    #Path to our data(volume
    # path: "/storage/redisData" #try this instead of /data1 
    path: "/storage/data1" 