apiVersion: v1
kind: Service
metadata:
  name: growvia-redis
  namespace: production
spec:
  # with this ClusterIP we can only access to it within the cluster, not from outside
  type: ClusterIP
  selector:
    # so any Pod with this selector  that pod will have this service attach
    app: growvia-redis 
  ports:
  - name: growvia-redis
    port: 6379
    targetPort: 6379