#For production the statefulSet (that contains storage) is used (handle more replicas) but we will use
#but we will use 'Deployment' fro local dev

apiVersion: apps/v1
kind: Deployment
metadata:
  name: growvia-rabbitmq
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: growvia-rabbitmq
  template:
    metadata:
      labels:
        app: growvia-rabbitmq
    spec:
      containers:
      - name: growvia-rabbitmq
        #Image that we used(tested) in docker
        image: rabbitmq:4.0.5-management-alpine
        #Password will be stored in 'secret' file 
        env: 
        - name: RABBITMQ_DEFAULT_USER
          #value: growvia
          valueFrom:
              secretKeyRef:
                name: secret-data
                key: growvia-rabbitmq-user
                
        - name: RABBITMQ_DEFAULT_PASS
          #value: growviapassword
          valueFrom:
              secretKeyRef:
                name: secret-data
                key: growvia-rabbitmq-password
        resources:
          limits:
            memory: "1Gi"
            cpu: "0.5"
          requests:
            memory: 150Mi
            cpu: 100m
        ports:
        - name: queue
          containerPort: 5672
          protocol: TCP
        - name: mgmt
          containerPort: 15672
          protocol: TCP
        volumeMounts:
          - name: rabbitmq-storage
            mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-storage
          persistentVolumeClaim:
            claimName: rabbitmq-pvc