apiVersion: v1
kind: Service
metadata:
  name: growvia-rabbitmq
  namespace: production
spec:
  type: ClusterIP
  selector:
    #Every queue with this name ‘app:growvia-rabbitmq), 
    #We set ‘label’ tab to queue.yams as app:growvia-rabbitmq
    app: growvia-rabbitmq
  ports:
  - name: queue
    port: 5672
    # Want to target port ‘queue’ from queue.yaml
    targetPort: queue
    protocol: TCP
  - name: mgmt
    port: 15672
    targetPort: mgmt
    protocol: TCP